In [29]:
#Function get DCT feture vector 
from scipy.fftpack import dct, idct
from skimage.measure import compare_mse
from ipynb.fs.full.lbp import EkstraksiCiri
from skimage.feature import local_binary_pattern
import cv2
import numpy
import math

In [36]:
class DCT:
    def dct2(self, block):
        return dct(dct(block.T, norm='ortho').T, norm='ortho')

    def idct2(self, block):
        return idct(idct(block.T, norm='ortho').T, norm='ortho')

    #Extract DCT features of Image
    def zigZag(self, mat):
        rows=len(mat)
        columns=len(mat[0])

        solution=[[] for i in range(rows+columns-1)] 

        for i in range(rows): 
            for j in range(columns): 
                sum=i+j 
                if(sum%2 ==0): 

                    #add at beginning 
                    solution[sum].insert(0,mat[i][j]) 
                else: 

                    #add at end of the list 
                    solution[sum].append(mat[i][j]) 

        return numpy.concatenate(solution,axis=None)

    def getDctFeatures(self, img,num):
        #Init
        n=math.ceil(sqrt(num))
        cD = self.dct2(img)
        cD = self.zigZag(cD[0:n,0:n])
        cD = cD[0:num]
        return (cD/numpy.sqrt(cD @ cD))
    
    def getDCT(self, dt):
        hfDCT=[]
        nFeat=48
        for i in range(dt.shape[0]):
            t=self.getDctFeatures(dt[i],nFeat)
            hfDCT=numpy.concatenate((hfDCT, t), axis=None)

        hfDCT=numpy.reshape(hfDCT,(round(hfDCT.size/nFeat),nFeat))
        return hfDCT

In [44]:
dcT = DCT()
img = cv2.imread("a0.jpg")
grayscale = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(grayscale)
lbp = local_binary_pattern(grayscale, 1, 4)
result_lbp = numpy.array([lbp])
result_lbp

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


array([[[1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.],
        ...,
        [1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.]]])

In [39]:
result_dct = dcT.getDCT(result_lbp)
result_dct

array([[ 9.98490032e-01,  1.68117126e-02, -3.04548279e-03,
         2.75170385e-02, -2.92739923e-03, -1.35400488e-02,
         8.99300659e-03,  2.21262515e-04, -1.57356353e-03,
         7.95601130e-03, -1.68431780e-02,  6.84567706e-03,
        -2.38608646e-03,  2.30381057e-03, -1.61764109e-02,
         1.32932125e-02, -3.16272840e-04,  9.42993042e-03,
        -1.80078804e-04,  2.23666672e-03, -9.97472557e-03,
         5.29523720e-03, -6.38924544e-03,  1.69259385e-04,
        -4.95736731e-03,  2.59584503e-03,  1.00555724e-03,
        -1.34140959e-02,  1.24696445e-03,  2.93645885e-03,
         7.30128991e-04, -8.24213162e-03, -8.22448798e-04,
        -2.74789862e-03,  1.92308670e-03,  3.32924975e-03,
        -7.43810932e-03, -2.30429909e-03, -3.05462820e-03,
        -3.33762315e-03, -1.49647934e-03, -7.14136891e-04,
         5.78823028e-03,  1.13808498e-02,  1.99770915e-03,
         2.10593830e-03,  4.26835794e-03,  3.58967372e-04]])

In [40]:
16*3

48